<template>
  <div class="container my-4">
    <h1 class="text-center">Slot Statistics</h1>

    <!-- Navigation -->
    <nav class="nav-bar d-flex justify-content-center gap-4 my-3">
      <router-link to="/admin" class="nav-link">Home</router-link>
      <router-link to="/admin/users" class="nav-link">Users</router-link>
      <router-link to="/admin/search" class="nav-link">Search</router-link>
      <router-link to="/admin/charts" class="nav-link">Charts</router-link>
    </nav>

    <!-- Logout Button -->
    <div class="d-flex justify-content-end mb-3">
      <button class="btn btn-dark rounded-pill px-4 py-2" @click="logout">Log Out</button>
    </div>

    <!-- Chart Selector -->
    <div class="d-flex justify-content-center mb-4">
      <select v-model="selectedChart" class="form-select w-auto">
        <option value="occupancy">Occupied vs Non-Occupied (Bar)</option>
        <option value="pie">Total Occupancy (Pie)</option>
        <option value="revenue">Revenue by Location (Bar)</option>
      </select>
    </div>

    <!-- Chart Display -->
    <div style="display: flex; justify-content: center; height: 70vh;">
      <div style="width: 700px; height: 500px;">
        <Bar v-if="selectedChart === 'occupancy'" :data="barChartData" :options="barChartOptions" />
        <Pie v-else-if="selectedChart === 'pie'" :data="pieChartData" :options="pieChartOptions" />
        <Bar v-else-if="selectedChart === 'revenue'" :data="revenueChartData" :options="revenueChartOptions" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import { Bar, Pie } from 'vue-chartjs'
import {
  Chart as ChartJS,
  Title, Tooltip, Legend,
  BarElement, ArcElement, CategoryScale, LinearScale
} from 'chart.js'

// Register Chart.js components
ChartJS.register(Title, Tooltip, Legend, BarElement, ArcElement, CategoryScale, LinearScale)

const selectedChart = ref('occupancy')

const barChartData = ref({ labels: [], datasets: [] })
const pieChartData = ref({ labels: [], datasets: [] })
const revenueChartData = ref({ labels: [], datasets: [] })

const barChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { position: 'top' },
    title: { display: true, text: 'Occupied vs Non-Occupied Slots by Location' }
  }
}

const pieChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { position: 'bottom' },
    title: { display: true, text: 'Total Occupancy Overview (All Locations)' }
  }
}

const revenueChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { position: 'top' },
    title: { display: true, text: 'Revenue Generated by Location' }
  }
}

const router = useRouter()

function logout() {
  localStorage.clear()
  router.push({ name: 'login' })
}

onMounted(async () => {
  try {
    const res = await axios.get('http://localhost:5000/api/slotStats/admin')
    const data = res.data

    barChartData.value = {
      labels: data.bar_chart.map(item => item.location),
      datasets: [
        {
          label: 'Occupied Slots',
          backgroundColor: '#f87171',
          data: data.bar_chart.map(item => item.occupied)
        },
        {
          label: 'Non-Occupied Slots',
          backgroundColor: '#60a5fa',
          data: data.bar_chart.map(item => item.non_occupied)
        }
      ]
    }

    pieChartData.value = {
      labels: ['Occupied', 'Non-Occupied'],
      datasets: [
        {
          label: 'Total Slots',
          backgroundColor: ['#f87171', '#60a5fa'],
          data: [data.pie_chart.occupied, data.pie_chart.non_occupied]
        }
      ]
    }

    revenueChartData.value = {
      labels: data.revenue_chart.map(item => item.location),
      datasets: [
        {
          label: 'Revenue ₹',
          backgroundColor: '#34d399',
          data: data.revenue_chart.map(item => item.revenue)
        }
      ]
    }
  } catch (error) {
    console.error('Error fetching chart data:', error)
  }
})
</script>

<style>
.container {
  max-width: 800px;
}
</style>
