# Generated by Django 5.2.4 on 2025-08-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('lotId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('maxSlots', models.IntegerField()),
                ('price', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.locations')),
            ],
            options={
                'db_table': 'lots',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('slotId', models.IntegerField()),
                ('isOccupied', models.BooleanField(default=False)),
                ('lotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lots')),
            ],
            options={
                'db_table': 'slots',
                'unique_together': {('slotId', 'lotId')},
            },
        ),
        migrations.CreateModel(
            name='OccupiedSlot',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('slotId', models.IntegerField()),
                ('vehicleNo', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('lotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lots')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'occupied_slot',
                'unique_together': {('slotId', 'lotId')},
            },
        ),
    ]
